version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/app/webapp
    depends_on:
      - webapp
    restart: unless-stopped

  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app
      - ./bot/applications.db:/app/applications.db
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
      - ./bot/applications.db:/app/applications.db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    restart: unless-stopped

volumes:
  database_data: